### ISSUE TITLE
Reccuring Drop-in Questions

### ISSUE THREAD

**Issue by Vali1420** [adyen-examples/adyen-node-online-payments#127]
1. I saw these days that the recurring option is deprecated, and it will be available only for pay by link? 
![Screenshot 2023-06-09 133145](https://github.com/adyen-examples/adyen-node-online-payments/assets/80223020/4ddb2128-6d52-482c-8a86-3c34c64470e1)

2. When I am using session payment, sometimes I receive the recurring token in the webhook, and sometimes not. Maybe is a bug from adyen..
![image](https://github.com/adyen-examples/adyen-node-online-payments/assets/80223020/3530c343-8db1-4baa-8693-0a2b5c6dbe2f)
![image](https://github.com/adyen-examples/adyen-node-online-payments/assets/80223020/db9d1d2f-146d-4992-9450-d4ffc6e9e0b0)

**Comment by Vali1420** [comment]
Thanks is advance :)

**Comment by Kwok-he-Chu** [comment]
> 1. I saw these days that the recurring option is deprecated, and it will be available only for pay by link?

The options in the screenshot under `Checkout Settings` are used for a different purpose.

> 2. When I am using session payment, sometimes I receive the recurring token in the webhook, and sometimes not. Maybe is a bug from adyen..

You cannot always expect the recurringDetailReference in the API response, we recommend the asynchronous flow as the token creation takes a bit longer. You should rely on the ["RECURRING_CONTRACT" webhook](https://docs.adyen.com/development-resources/webhooks/webhook-types#non-default-event-codes) to get the recurringDetailReference. 

If you're having trouble getting "RECURRING_CONTACT" to appear, please contact support as they might need to enable some configuration for the asynchronous flow depending on your use-case. You can read more here on how that flow looks like: https://docs.adyen.com/online-payments/tokenization/create-and-use-tokens?tab=subscriptions_2#pending-and-refusal-result-codes-1

**Comment by Kwok-he-Chu** [comment]
Closing this ticket, feel free to reopen it if the issue persists @Vali1420 👍
