### ISSUE TITLE
Updated example for version 5.0.0

### ISSUE THREAD

**Issue by tmadison-gpsw** [adyen-examples/adyen-node-online-payments#13]
Hello, I was wondering if this will be updated for @adyen/adyen-web version 5.0.x? Or can you provide us with a link to how to integrate the 5.0.0 version of the Dropin component with a Reat/Nodejs app?

**Comment by jlengrand** [comment]
Hey there, the react repo already contains the sessions update:   https://github.com/adyen-examples/adyen-react-online-payments.

This repo will be done any time now, see #14 

Let me know if you run into more issues!
