### ISSUE TITLE
Introduce /sessions endpoint

### ISSUE THREAD

**Issue by gcatanese** [adyen-examples/adyen-node-online-payments#14]
Integrate the new /sessions endpoint to leverage on a single API call

**Comment by xiaofeihui** [comment]
how to set adyen form with pix method? we want to add socialSecurityNumber form when i selected pix method

**Comment by gcatanese** [comment]
If you are using the latest version (`/sessions` endpoint, already merged in main see PR #15) you can pass the **socialSecurityNumber** in the JSON payload of the request.

See https://docs.adyen.com/payment-methods/pix/web-drop-in#api-reference

**Comment by gcatanese** [comment]
I am closing this as it is implemented by PR #15. @xiaofeihui I have answered your question, if you still need some help please create a new issue (if you have a reproducible problem) or a Stackoverflow question.
