### ISSUE TITLE
font scale effect is creating issue with payment layout

### ISSUE THREAD

**Issue by miniunikove** [adyen-examples/adyen-node-online-payments#212]
![177FCA6D-E52E-4569-B7B2-22AD766C9EFD](https://github.com/adyen-examples/adyen-node-online-payments/assets/142818535/4a5d9990-c2a7-42b9-884c-ade56f02d1d6)

**Comment by gcatanese** [comment]
Thank you for reporting this problem. 
The goal of the repository is to show how to integrate the Adyen platform (using Web drop-in and the Node.js API library) and perform a test payment, therefore we don't plan to address issues like mobile device responsiveness. But we will take into consideration your feedback if we create a new sample or significantly refactor this demo. Thank you!
